"""Deterministic synthetic experiment: ragvitals over a Gemma-vs-Claude swap.

The point of this script is to produce the article's headline numbers
reproducibly, without anyone needing GPUs, Anthropic API keys, or HuggingFace
gated-model access. We synthesize embeddings, retrieval scores, and judge
scores in the *shape* you actually observe when you swap from a Claude-tuned
RAG to a Gemma 4 generator on the same corpus:

  - QueryDistribution stays flat (same users, same queries)
  - EmbeddingDrift stays flat (same embedder)
  - RetrievalRelevance stays flat (same retriever / index)
  - ResponseQuality moves down (Gemma 4 is a different family with different
    refusal / faithfulness behavior than Claude Sonnet 4.5)
  - JudgeDrift fires only if the judge model itself changed

The synthetic data is a faithful representation of what we see in real swaps,
not a fabrication of empirical results from any specific run. The companion
`real_models_run.py` script reproduces against actual Gemma 4 + Claude.

Run:
    python demo/synthetic_run.py
"""

from __future__ import annotations

import argparse
import json
import random
import statistics
from datetime import datetime, timedelta
from pathlib import Path

from ragvitals import (
    Detector,
    EmbeddingDrift,
    InMemorySink,
    JudgeDrift,
    QueryDistribution,
    ResponseQuality,
    RetrievalRelevance,
    Trace,
)

DATA_DIR = Path(__file__).parent / "data"
SEED = 20260524  # determinism: same seed → same numbers in the article


def _gauss_vec(rng: random.Random, dim: int, scale: float = 1.0) -> list[float]:
    return [rng.gauss(0, scale) for _ in range(dim)]


def _shifted_vec(rng: random.Random, dim: int, shift: float = 0.05) -> list[float]:
    return [rng.gauss(shift, 1.0) for _ in range(dim)]


def _faithfulness_score(rng: random.Random, base_mean: float) -> float:
    """Mimic LLM-as-judge output. Tail-clipped to [0, 1]."""
    s = rng.gauss(base_mean, 0.04)
    return max(0.0, min(1.0, s))


def _build_detector() -> Detector:
    q = QueryDistribution(degraded_z=2.5, warn_z=1.7)
    q.set_reference([[1.0, 0.0] for _ in range(50)])

    e = EmbeddingDrift(degraded_z=2.5, warn_z=1.7)
    e.set_reference([[1.0, 0.0] for _ in range(50)])

    j = JudgeDrift(score_key="faithfulness", warn_abs=0.04, degraded_abs=0.12)
    # Reference: what the judge said on day 0 for our reference probes.
    j.set_reference({f"ref-{i}": 0.92 + i * 0.001 for i in range(10)})

    return Detector(
        dimensions=[
            q,
            RetrievalRelevance(metric="hit_rate", k=10, warn_z=1.7, degraded_z=2.5),
            e,
            ResponseQuality(score_keys=["faithfulness", "relevance"], warn_z=1.7, degraded_z=2.5),
            j,
        ],
        sinks=[InMemorySink()],
    )


def _baseline_phase(det: Detector, rng: random.Random, n_windows: int = 8, traces_per_window: int = 50) -> None:
    """Eight days of Claude-tuned baseline traffic + 10 reference probes/day.

    The live traffic (no reference_id) feeds QueryDistribution, EmbeddingDrift,
    RetrievalRelevance, and ResponseQuality. The reference probes (with
    reference_id) feed JudgeDrift only — they're a frozen benchmark, not
    representative user traffic.
    """
    base_ts = datetime(2026, 5, 1)
    for day in range(n_windows):
        # Live traffic
        for i in range(traces_per_window):
            det.ingest(Trace(
                timestamp=base_ts + timedelta(days=day, minutes=i),
                query_embedding=[1.0 + rng.gauss(0, 0.02), rng.gauss(0, 0.02)],
                retrieval_scores=[0.91 + rng.gauss(0, 0.02), 0.83 + rng.gauss(0, 0.02)],
                relevance_labels=[1, 0, 0, 0, 0] if rng.random() < 0.86 else [0, 0, 0, 0, 0],
                judge_scores={
                    "faithfulness": _faithfulness_score(rng, 0.92),
                    "relevance": _faithfulness_score(rng, 0.90),
                },
                metadata={"model": "claude-sonnet-4-5"},
            ))
        # Reference probes (re-judged daily)
        for i in range(10):
            det.ingest(Trace(
                timestamp=base_ts + timedelta(days=day, hours=23),
                judge_scores={
                    "faithfulness": _faithfulness_score(rng, 0.92 + i * 0.001),
                },
                metadata={"reference_id": f"ref-{i}", "model": "claude-sonnet-4-5",
                          "probe": True},
            ))
        det.commit_window()


def _gemma_phase(det: Detector, rng: random.Random, traces: int = 50) -> None:
    """One window of live traffic generated by Gemma 4 (no reference probes).

    Embedding distribution and retrieval relevance are unchanged (same retriever).
    Faithfulness drops on average; relevance drops slightly. Same queries, same
    users, same docs — the gen-model swap is the only thing that moved.

    Note we deliberately do NOT set `reference_id` here. Reference probes are a
    separate stream (see _judge_drift_phase) so that swapping the generator
    does not accidentally trip JudgeDrift. JudgeDrift is for "is my judge
    drifting?", not "did my generator change?". Keeping the streams separate
    is the difference between a useful alarm and a flaky one.
    """
    base_ts = datetime(2026, 5, 9)
    for i in range(traces):
        det.ingest(Trace(
            timestamp=base_ts + timedelta(minutes=i),
            query_embedding=[1.0 + rng.gauss(0, 0.02), rng.gauss(0, 0.02)],
            retrieval_scores=[0.91 + rng.gauss(0, 0.02), 0.83 + rng.gauss(0, 0.02)],
            relevance_labels=[1, 0, 0, 0, 0] if rng.random() < 0.86 else [0, 0, 0, 0, 0],
            judge_scores={
                "faithfulness": _faithfulness_score(rng, 0.78),  # Gemma is more terse + cautious
                "relevance":    _faithfulness_score(rng, 0.87),  # slight relevance dip
            },
            metadata={"model": "gemma-4-9b"},  # no reference_id; JudgeDrift will not pick this up
        ))


def _judge_drift_phase(det: Detector, rng: random.Random, n_probes: int = 50) -> None:
    """One window where the JUDGE itself changed.

    Reference probes get re-scored by a new judge model that systematically
    rates everything about +0.15 higher than the day-0 judge. The 50 probes
    span the 10 reference IDs, 5 reruns each, so JudgeDrift has enough sample
    to alarm.

    The article's secondary point: judge drift and response-quality drift
    are different things and ragvitals separates them.
    """
    base_ts = datetime(2026, 5, 10)
    for i in range(n_probes):
        ref_id = i % 10
        det.ingest(Trace(
            timestamp=base_ts + timedelta(minutes=i),
            judge_scores={
                "faithfulness": _faithfulness_score(rng, 1.10),  # systematically higher
            },
            metadata={"reference_id": f"ref-{ref_id}", "model": "claude-sonnet-4-5",
                      "probe": True, "judge_version": "v2"},
        ))


def print_report(label: str, report) -> None:
    print(f"\n=== {label} ===")
    for d in report.dimensions:
        val = f"{d.value:.4f}" if isinstance(d.value, (int, float)) else "n/a"
        z = f"z={d.z_score:+.2f}" if isinstance(d.z_score, (int, float)) else ""
        print(f"  {d.name:35s}  {d.severity.value:9s}  value={val:>7s}  {z:>10s}  n={d.sample_size}")
    print(f"  degraded: {report.degraded}")
    print(f"  warned:   {report.warned}")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--phase", choices=["baseline", "swap", "judge", "all"], default="all")
    args = parser.parse_args()

    rng = random.Random(SEED)
    det = _build_detector()

    _baseline_phase(det, rng)
    baseline_report = det.report()
    if args.phase in ("baseline", "all"):
        print_report("After 8 days of Claude baseline", baseline_report)
        det.commit_window()

    if args.phase in ("swap", "all"):
        _gemma_phase(det, rng)
        swap_report = det.report()
        print_report("After 1 day of Gemma 4 generator (same retriever, same judge)", swap_report)
        det.commit_window()

    if args.phase in ("judge", "all"):
        _judge_drift_phase(det, rng)
        judge_report = det.report()
        print_report("After 1 day of a drifted judge (same generator, same retriever)", judge_report)


if __name__ == "__main__":
    main()
